 CFLAGS+=-pthread
 LDFLAGS+=-pthread

PROGS=

-rwxr-xr-x  1 root root 8839 May 17 20:17 10.add_ok
-rw-r--r--  1 root root  773 May 17 20:17 10.add_ok.c
-rwxr-xr-x  1 root root 8624 May 17 20:35 11.abcd
-rw-r--r--  1 root root  826 May 17 20:36 11.abcd.c
-rwxr-xr-x  1 root root 7879 Apr 20  2017 12.mutex_dead_lock
-rw-r--r--  1 root root  905 May 17 20:38 12.mutex_dead_lock.c
-rwxr-xr-x. 1 root root 9672 Nov  1  2016 13.primer0_pool_busy
-rw-r--r--. 1 root root 1974 Nov  1  2016 13.primer0_pool_busy.c
-rwxr-xr-x. 1 root root 8008 Feb 19  2017 14.pthread_share_stack_heap_var
-rw-r--r--  1 root root 1202 Dec  4 15:14 14.pthread_share_stack_heap_var.c
drwxr-xr-x. 2 root root 4096 Jul 14  2016 15.mytbf_mt_sched_yield
drwxr-xr-x. 2 root root 4096 Jul 26  2016 16.mytbf_mt_cond
-rwxr-xr-x. 1 root root 9913 Jan 23  2017 17.primer0_cond_pool
-rw-r--r--. 1 root root 1936 Aug 27  2016 17.primer0_cond_pool.c
-rwxr-xr-x. 1 root root 9679 Aug 25  2016 18.primer0_busy_pool_sleep
-rw-r--r--. 1 root root 1747 Aug 25  2016 18.primer0_busy_pool_sleep.c
-rwxr-xr-x. 1 root root 9917 Jul 14  2016 19.primer0_cond_pool_sleep
-rw-r--r--. 1 root root 1910 Jul 14  2016 19.primer0_cond_pool_sleep.c
-rw-r--r--  1 root root  457 Dec  3 22:38 1.creat1.c
-rwxr-xr-x. 1 root root 9802 Jul 14  2016 20.abcd_e
-rw-r--r--. 1 root root 1343 Jul 14  2016 20.abcd_e.c
drwxr-xr-x. 2 root root 4096 Jul 14  2016 21.mysem
-rwxr-xr-x. 1 root root 7773 Jul 14  2016 21.thread_study
-rw-r--r--. 1 root root  674 Jul 14  2016 21.thread_study.c
-rwxr-xr-x. 1 root root 8639 Jul 14  2016 22.create
-rw-r--r--. 1 root root  902 Jul 14  2016 22.create.c
drwxr-xr-x. 2 root root 4096 Jul 24  2016 23.process_vs_thread
-rw-r--r--. 1 root root  996 Jul 25  2016 24.pthread_create_fork.c
-rwxr-xr-x. 1 root root 8154 Jul 26  2016 25.pthread_create_pthread_create
-rw-r--r--. 1 root root  795 Jul 26  2016 25.pthread_create_pthread_create.c
drwxr-xr-x. 2 root root 4096 Sep  9  2016 26.mypipe
-rw-r--r--  1 root root 1894 Dec  8 17:27 27.pthread_detach.c
-rwxr-xr-x. 1 root root 9656 Nov  4  2016 28.pthread_with_time
-rw-r--r--. 1 root root 1543 Feb 19  2017 28.pthread_with_time.c
-rwxr-xr-x  1 root root 7964 Apr 21  2017 29.pthread_mutex_trylock
-rw-r--r--  1 root root  965 Apr 21  2017 29.pthread_mutex_trylock.c
-rw-r--r--  1 root root  701 Dec  8 18:15 2.pthread_join.c
-rw-r--r--  1 root root 1482 Apr 21  2017 30.pthread_setspecific.c
-rwxr-xr-x  1 root root 9729 Jan 23 22:45 31.redis_bio
-rw-r--r--  1 root root 1527 Jan 23 22:49 31.redis_bio.c
-rwxr-xr-x. 1 root root 8325 Jul 14  2016 3.pthead_exit
-rw-r--r--. 1 root root  616 Jul 14  2016 3.pthead_exit.c
-rwxr-xr-x. 1 root root 8889 Jul 14  2016 4.thread_clean
-rw-r--r--. 1 root root  761 Jul 14  2016 4.thread_clean.c
-rwxr-xr-x. 1 root root 7431 Jul 14  2016 5.thread_var
-rw-r--r--. 1 root root  528 Jul 14  2016 5.thread_var.c
-rw-r--r--. 1 root root  784 Jul 14  2016 6.primer00.c
-rwxr-xr-x. 1 root root 7748 Sep 21  2016 7.primer0_ugly
-rw-r--r--. 1 root root  753 Jul 14  2016 7.primer0_ugly.c
-rwxr-xr-x. 1 root root 8241 Jul 14  2016 8.primer0_e
-rw-r--r--. 1 root root  897 Jul 14  2016 8.primer0_e.c
-rwxr-xr-x. 1 root root 8214 Jul 14  2016 9.add
-rw-r--r--. 1 root root  619 Jul 14  2016 9.add.c

