 CFLAGS+=-pthread
 LDFLAGS+=-pthread

PROGS= 1.creat1 2.pthread_join 3.pthead_exit 4.thread_clean 5.thread_var \
	6.primer00 7.primer0_ugly 8.primer0_e 9.add 10.add_ok 11.abcd \
	12.mutex_dead_lock 13.primer0_pool_busy 14.pthread_share_stack_heap_var \
	17.primer0_cond_pool 18.primer0_busy_pool_sleep 19.primer0_cond_pool_sleep \
	20.abcd_e 21.thread_study 22.create 24.pthread_create_fork \
	25.pthread_create_pthread_create 27.pthread_detach 28.pthread_with_time \
	29.pthread_mutex_trylock 30.pthread_setspecific 31.redis_bio

clean:
	rm -f $(PROGS) *.o


