include ../Makefile.inc

GEN_EXE = 1.front_processgroup t_setsid catch_SIGHUP disc_SIGHUP

EXE = ${GEN_EXE} ${LINUX_EXE}

all : ${EXE}

allgen : ${GEN_EXE}

clean : 
	${RM} ${EXE} *.o

showall :
	@ echo ${EXE}

${EXE} : ${TLPI_LIB}		# True as a rough approximation
