all:
	gcc 128bytes_mycpy_read.c		-o	128bytes_mycpy_read
	gcc 256bytes_mycpy_read.c		-o	256bytes_mycpy_read
	gcc 512bytes_mycpy_read.c		-o	512bytes_mycpy_read
	gcc 1kbytes_mycpy_read.c		-o	1kbytes_mycpy_read
	gcc 4kbytes_mycpy_read.c		-o	4kbytes_mycpy_read
	gcc 8kbytes_mycpy_read.c		-o	8kbytes_mycpy_read
	gcc 32kbytes_mycpy_read.c		-o	32kbytes_mycpy_read
	gcc 64kbytes_mycpy_read.c		-o	64kbytes_mycpy_read
	gcc 128kbytes_mycpy_read.c		-o	128kbytes_mycpy_read
	gcc 256kbytes_mycpy_read.c		-o	256kbytes_mycpy_read
	gcc 512kbytes_mycpy_read.c		-o	512kbytes_mycpy_read
	gcc 1m_mycpy_read.c       		-o	1m_mycpy_read
	gcc 7m_mycpy_read.c       		-o	7m_mycpy_read
	gcc 8m_mycpy_read.c       		-o	8m_mycpy_read
	gcc 10m_mycpy_read.c      		-o	10m_mycpy_read
	gcc 16m_mycpy_read.c      		-o	16m_mycpy_read
	gcc make_1.pdf.c 				-o  make_1.pdf

clean:
	$(RM) 128bytes_mycpy_read 256bytes_mycpy_read 512bytes_mycpy_read 1kbytes_mycpy_read 4kbytes_mycpy_read 8kbytes_mycpy_read 32kbytes_mycpy_read 64kbytes_mycpy_read 128kbytes_mycpy_read 256kbytes_mycpy_read 512kbytes_mycpy_read 1m_mycpy_read 7m_mycpy_read 8m_mycpy_read 10m_mycpy_read 16m_mycpy_read make_1.pdf 1.pdf 2.pdf
